# This file is used to run the application in PRODUCTION mode.
# It is meant to be used as a standalone file or as a base file
# for a more complex setup.

name: rokis-portfolio-prod

services:

  web:
    build:
      context: .
      target: prod
    container_name: portfolio-django-prod
    ports:
      - "${DJANGO_PORT}:8000"
    env_file: .env
    volumes:
      - ./run:/app/run
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: portfolio-postgres-prod
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
