# This file is used to run the application in DEVELOPMENT mode.
# It is ment to be used in conjunction with PRODUCTION docker-compose
# file to be as close as possible to the production environment.

name: rokis-portfolio-dev

services:

  web:
    container_name: portfolio-django-dev

  db:
    container_name: portfolio-postgres-dev
    volumes:
      - rokis_portfolio_dev_postgres_data:/var/lib/postgresql/data

networks:
  rokis_portfolio_dev_network:
    name: rokis-portfolio-dev-network

volumes:
  rokis_portfolio_dev_postgres_data:
