# This file is used to run the application in DEVELOPMENT mode.
# It is ment to be used in conjunction with PRODUCTION docker-compose
# file to be as close as possible to the production environment.

name: portfolizer-dev

services:

  web:
    container_name: portfolizer-django-dev

  db:
    container_name: portfolizer-postgres-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  portfolizer_dev_network:
    name: portfolizer-dev-network

volumes:
  postgres_data:
