# This file is used to run the application in LOCAL/DEVELOPMENT mode.
# It is not ment to be used in conjunction with another docker-compose
# file, but rather to be used as a standalone file.

services:

  web:
    build:
      context: .
      target: local
    container_name: django
    ports:
      - "${DJANGO_PORT}:8000"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

volumes:
  postgres_data:
