# Generated by Django 5.1.2 on 2024-11-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='seventh_left_segment',
            field=models.CharField(choices=[('contact', 'Contact'), ('personal_details', 'Personal Details'), ('links', 'Links'), ('skills', 'Skills'), ('languages', 'Languages'), ('internship', 'Internship'), ('education', 'Education')], default='education', max_length=20, verbose_name='seventh segment in left column'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='fifth_left_segment',
            field=models.CharField(choices=[('contact', 'Contact'), ('personal_details', 'Personal Details'), ('links', 'Links'), ('skills', 'Skills'), ('languages', 'Languages'), ('internship', 'Internship'), ('education', 'Education')], default='languages', max_length=20, verbose_name='fifth segment in left column'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='first_left_segment',
            field=models.CharField(choices=[('contact', 'Contact'), ('personal_details', 'Personal Details'), ('links', 'Links'), ('skills', 'Skills'), ('languages', 'Languages'), ('internship', 'Internship'), ('education', 'Education')], default='contact', max_length=20, verbose_name='first segment in left column'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='fourth_left_segment',
            field=models.CharField(choices=[('contact', 'Contact'), ('personal_details', 'Personal Details'), ('links', 'Links'), ('skills', 'Skills'), ('languages', 'Languages'), ('internship', 'Internship'), ('education', 'Education')], default='skills', max_length=20, verbose_name='fourth segment in left column'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='second_left_segment',
            field=models.CharField(choices=[('contact', 'Contact'), ('personal_details', 'Personal Details'), ('links', 'Links'), ('skills', 'Skills'), ('languages', 'Languages'), ('internship', 'Internship'), ('education', 'Education')], default='personal_details', max_length=20, verbose_name='second segment in left column'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='sixth_left_segment',
            field=models.CharField(choices=[('contact', 'Contact'), ('personal_details', 'Personal Details'), ('links', 'Links'), ('skills', 'Skills'), ('languages', 'Languages'), ('internship', 'Internship'), ('education', 'Education')], default='internship', max_length=20, verbose_name='sixth segment in left column'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='third_left_segment',
            field=models.CharField(choices=[('contact', 'Contact'), ('personal_details', 'Personal Details'), ('links', 'Links'), ('skills', 'Skills'), ('languages', 'Languages'), ('internship', 'Internship'), ('education', 'Education')], default='links', max_length=20, verbose_name='third segment in left column'),
        ),
    ]
