# Generated by Django 5.1.2 on 2024-11-22 18:41

from django.db import migrations


def reorder_left_segments(apps, schema_editor):
    Portfolio = apps.get_model("portfolio", "Portfolio")
    for portfolio in Portfolio.objects.all():
        portfolio.first_left_segment = "contact"
        portfolio.second_left_segment = "personal_details"
        portfolio.third_left_segment = "links"
        portfolio.fourth_left_segment = "skills"
        portfolio.fifth_left_segment = "languages"
        portfolio.sixth_left_segment = "internship"
        portfolio.seventh_left_segment = "education"
        portfolio.save()


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0005_portfolio_seventh_left_segment_and_more'),
    ]

    operations = [
        migrations.RunPython(
            reorder_left_segments,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
