# Generated by Django 5.1.2 on 2024-11-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_reorder_left_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='about_me_segment_title',
            field=models.CharField(default='ABOUT ME', max_length=100, verbose_name='about me segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='contact_segment_title',
            field=models.CharField(default='CONTACT', max_length=100, verbose_name='contact segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='education_segment_title',
            field=models.CharField(default='EDUCATION', max_length=100, verbose_name='education segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='employment_segment_title',
            field=models.CharField(default='EMPLOYMENT HISTORY', max_length=100, verbose_name='employment segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='internship_segment_title',
            field=models.CharField(default='INTERNSHIP HISTORY', max_length=100, verbose_name='internship segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='languages_segment_title',
            field=models.CharField(default='LANGUAGES', max_length=100, verbose_name='languages segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='links_segment_title',
            field=models.CharField(default='LINKS', max_length=100, verbose_name='links segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='personal_details_segment_title',
            field=models.CharField(default='PERSONAL DETAILS', max_length=100, verbose_name='personal details segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projects_segment_title',
            field=models.CharField(default='RELEVANT PROJECTS', max_length=100, verbose_name='projects segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills_segment_title',
            field=models.CharField(default='SKILLS', max_length=100, verbose_name='skills segment title'),
        ),
    ]
