# Generated by Django 5.1.3 on 2024-11-24 13:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_about_me_segment_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='left_column_bg_color',
            field=colorfield.fields.ColorField(default='#303030', image_field=None, max_length=25, samples=None, verbose_name='left column background color'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='left_column_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='left column text color'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='right_column_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='right column background color'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='right_column_text_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='right column text color'),
        ),
    ]
