# Generated by Django 5.1.3 on 2024-11-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_portfolio_edit_btn_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='about_me_segment_title',
            field=models.CharField(blank=True, default='ABOUT ME', max_length=100, null=True, verbose_name='about me segment title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='contact_segment_title',
            field=models.CharField(blank=True, default='CONTACT', max_length=100, null=True, verbose_name='contact segment title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='education_segment_title',
            field=models.CharField(blank=True, default='EDUCATION', max_length=100, null=True, verbose_name='education segment title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='employment_segment_title',
            field=models.CharField(blank=True, default='EMPLOYMENT HISTORY', max_length=100, null=True, verbose_name='employment segment title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='internship_segment_title',
            field=models.CharField(blank=True, default='INTERNSHIP HISTORY', max_length=100, null=True, verbose_name='internship segment title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='languages_segment_title',
            field=models.CharField(blank=True, default='LANGUAGES', max_length=100, null=True, verbose_name='languages segment title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='links_segment_title',
            field=models.CharField(blank=True, default='LINKS', max_length=100, null=True, verbose_name='links segment title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='personal_details_segment_title',
            field=models.CharField(blank=True, default='PERSONAL DETAILS', max_length=100, null=True, verbose_name='personal details segment title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='projects_segment_title',
            field=models.CharField(blank=True, default='RELEVANT PROJECTS', max_length=100, null=True, verbose_name='projects segment title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills_segment_title',
            field=models.CharField(blank=True, default='SKILLS', max_length=100, null=True, verbose_name='skills segment title'),
        ),
    ]
