# Generated by Django 5.1.3 on 2024-11-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_portfolio_about_me_segment_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_en',
            field=models.CharField(max_length=100, null=True, verbose_name='degree'),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='degree'),
        ),
        migrations.AddField(
            model_name='education',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='education',
            name='description_sr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='education',
            name='location_en',
            field=models.CharField(max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='education',
            name='location_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='education',
            name='school_en',
            field=models.CharField(max_length=100, null=True, verbose_name='school'),
        ),
        migrations.AddField(
            model_name='education',
            name='school_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='school'),
        ),
        migrations.AddField(
            model_name='employment',
            name='company_en',
            field=models.CharField(max_length=100, null=True, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='employment',
            name='company_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='employment',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='employment',
            name='description_sr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='employment',
            name='location_en',
            field=models.CharField(max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='employment',
            name='location_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='employment',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='employment',
            name='title_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='internship',
            name='company_en',
            field=models.CharField(max_length=100, null=True, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='internship',
            name='company_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='internship',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='internship',
            name='description_sr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='internship',
            name='location_en',
            field=models.CharField(max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='internship',
            name='location_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='internship',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='internship',
            name='title_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='language',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='language',
            name='label_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='link',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='link',
            name='label_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='about_me_en',
            field=models.TextField(blank=True, null=True, verbose_name='about me'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='about_me_segment_title_en',
            field=models.CharField(blank=True, default='ABOUT ME', max_length=100, null=True, verbose_name='about me segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='about_me_segment_title_sr',
            field=models.CharField(blank=True, default='ABOUT ME', max_length=100, null=True, verbose_name='about me segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='about_me_sr',
            field=models.TextField(blank=True, null=True, verbose_name='about me'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='address_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address label'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='address_label_sr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address label'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='contact_segment_title_en',
            field=models.CharField(blank=True, default='CONTACT', max_length=100, null=True, verbose_name='contact segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='contact_segment_title_sr',
            field=models.CharField(blank=True, default='CONTACT', max_length=100, null=True, verbose_name='contact segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='education_segment_title_en',
            field=models.CharField(blank=True, default='EDUCATION', max_length=100, null=True, verbose_name='education segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='education_segment_title_sr',
            field=models.CharField(blank=True, default='EDUCATION', max_length=100, null=True, verbose_name='education segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='employment_segment_title_en',
            field=models.CharField(blank=True, default='EMPLOYMENT HISTORY', max_length=100, null=True, verbose_name='employment segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='employment_segment_title_sr',
            field=models.CharField(blank=True, default='EMPLOYMENT HISTORY', max_length=100, null=True, verbose_name='employment segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='filename_en',
            field=models.CharField(max_length=100, null=True, verbose_name='filename'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='filename_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='filename'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='internship_segment_title_en',
            field=models.CharField(blank=True, default='INTERNSHIP HISTORY', max_length=100, null=True, verbose_name='internship segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='internship_segment_title_sr',
            field=models.CharField(blank=True, default='INTERNSHIP HISTORY', max_length=100, null=True, verbose_name='internship segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='languages_segment_title_en',
            field=models.CharField(blank=True, default='LANGUAGES', max_length=100, null=True, verbose_name='languages segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='languages_segment_title_sr',
            field=models.CharField(blank=True, default='LANGUAGES', max_length=100, null=True, verbose_name='languages segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='links_segment_title_en',
            field=models.CharField(blank=True, default='LINKS', max_length=100, null=True, verbose_name='links segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='links_segment_title_sr',
            field=models.CharField(blank=True, default='LINKS', max_length=100, null=True, verbose_name='links segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='personal_details_segment_title_en',
            field=models.CharField(blank=True, default='PERSONAL DETAILS', max_length=100, null=True, verbose_name='personal details segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='personal_details_segment_title_sr',
            field=models.CharField(blank=True, default='PERSONAL DETAILS', max_length=100, null=True, verbose_name='personal details segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projects_segment_title_en',
            field=models.CharField(blank=True, default='RELEVANT PROJECTS', max_length=100, null=True, verbose_name='projects segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projects_segment_title_sr',
            field=models.CharField(blank=True, default='RELEVANT PROJECTS', max_length=100, null=True, verbose_name='projects segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='role_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='role_sr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills_segment_title_en',
            field=models.CharField(blank=True, default='SKILLS', max_length=100, null=True, verbose_name='skills segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills_segment_title_sr',
            field=models.CharField(blank=True, default='SKILLS', max_length=100, null=True, verbose_name='skills segment title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_sr',
            field=models.TextField(default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='role_en',
            field=models.CharField(max_length=100, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='project',
            name='role_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_en',
            field=models.CharField(max_length=255, null=True, verbose_name='technologies'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_sr',
            field=models.CharField(max_length=255, null=True, verbose_name='technologies'),
        ),
        migrations.AddField(
            model_name='skill',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='skill',
            name='label_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='label'),
        ),
    ]
