# Generated by Django 5.1.3 on 2024-12-01 22:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_education_degree_en_education_degree_sr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='language_btn_bg_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Language button background color'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='language_btn_svg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Language button SVG color'),
        ),
    ]
