# Generated by Django 5.1.3 on 2024-12-21 12:01

import apps.portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_portfolio_language_btn_bg_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technologies',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='technologies_en',
            new_name='tools_en',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='technologies_sr',
            new_name='tools_sr',
        ),
        migrations.AddField(
            model_name='project',
            name='tools_title',
            field=models.CharField(default='Tools', max_length=100, verbose_name='technologies title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, validators=[apps.portfolio.validators.SlugBlacklistValidator()], verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.CharField(max_length=255, verbose_name='tools'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools_en',
            field=models.CharField(max_length=255, null=True, verbose_name='tools'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools_sr',
            field=models.CharField(max_length=255, null=True, verbose_name='tools'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools_title',
            field=models.CharField(default='Tools', max_length=100, verbose_name='tools title'),
        ),
        migrations.AddField(
            model_name='project',
            name='tools_title_en',
            field=models.CharField(default='Tools', max_length=100, null=True, verbose_name='tools title'),
        ),
        migrations.AddField(
            model_name='project',
            name='tools_title_sr',
            field=models.CharField(default='Tools', max_length=100, null=True, verbose_name='tools title'),
        ),
    ]
