# Generated by Django 5.1.5 on 2025-02-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_technologies_project_tools_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start'], 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={'default_related_name': 'employments', 'ordering': ['-start'], 'verbose_name': 'Employment', 'verbose_name_plural': 'Employments'},
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={'default_related_name': 'internships', 'ordering': ['-start'], 'verbose_name': 'Internship', 'verbose_name_plural': 'Internships'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', '-level', 'created'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='shows_language_level',
            field=models.BooleanField(default=True, help_text='If enabled, the language level will be displayed as a progress bar under the language label.', verbose_name='shows language level'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='shows_skill_level',
            field=models.BooleanField(default=True, help_text='If enabled, the skill level will be displayed as a progress bar under the skill label.', verbose_name='shows skill level'),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
    ]
