name: CI

on:
  push:
    branches:
      - '**'  # Run on all branches

env:
  SECRET_KEY: dummy-secret-key

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run checks
        run: docker compose -f docker-compose.ci.yaml run web
