name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean Droplet
        run: |
          SSH_CMD="ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }}"
          $SSH_CMD 'cd /var/www/rokis-corner'
          $SSH_CMD 'git pull origin main'
          $SSH_CMD 'bash /var/www/rokis-corner/scripts/deploy'
