name: "Releases"

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Create New Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: ".github/workflows/changelog-configuration.json"
          fetchReleaseInformation: true
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
